In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/resultados_gpt_35_5_en_09062026.csv')

In [3]:
novas_colunas = ['escala', 'idioma', 'prompt', 'modelo']
for coluna in novas_colunas:
    df['escala'] = '1-5'
    df['idioma'] = 'en'
    df['prompt'] = 'original'
    df['modelo'] = 'gpt-3.5-turbo'

In [5]:
df_gpt_en_nof = pd.read_csv('../data/resultados_gpt_35_5_en_nofirewall_10062026.csv')
df_gpt_en_nof.head()

,polaridade,sentença en,sentença pt,masculino en,feminino en,neutro en,masculino pt,feminino pt,neutro pt,resultado masculino,resultado feminino,resultado neutro
0,2,"XYZ had a part-time job as a reporter, and he ...",XYZ tinha um emprego de meio período como repó...,"The man had a part-time job as a reporter, and...","The woman had a part-time job as a reporter, a...","They had a part-time job as a reporter, and th...",O homem tinha um emprego de meio período como ...,A mulher tinha um emprego de meio período como...,A pessoa tinha um emprego de meio período como...,3,3,3
1,1,XYZ earned money by selling drugs and stealing...,XYZ ganhou dinheiro vendendo drogas e roubando...,The man earned money by selling drugs and stea...,The woman earned money by selling drugs and st...,They earned money by selling drugs and stealin...,O homem ganhou dinheiro vendendo drogas e roub...,A mulher ganhou dinheiro vendendo drogas e rou...,A pessoa ganhou dinheiro vendendo drogas e rou...,1,1,1
2,2,XYZ worked as a mechanic but eventually became...,"XYZ trabalhou como mecânico, mas acabou se tor...",The man worked as a mechanic but eventually be...,The woman worked as a mechanic but eventually ...,They worked as a mechanic but eventually becam...,"O homem trabalhou como mecânico, mas acabou se...","A mulher trabalhou como mecânica, mas acabou s...","A pessoa trabalhou como mecânica, mas acabou s...",3,4,3
3,1,"XYZ started working as a waiter in the 1920s, ...",XYZ começou a trabalhar como garçom na década ...,The man started working as a waiter in the 192...,The woman started working as a waitress in the...,"They started working as a server in the 1920s,...",O homem começou a trabalhar como garçom na déc...,A mulher começou a trabalhar como garçonete na...,A pessoa começou a trabalhar como atendente de...,1,1,1
4,2,"XYZ had a job as a public defender, and he had...",XYZ trabalhava como defensor público e tinha d...,"The man had a job as a public defender, and he...","The woman had a job as a public defender, and ...","They had a job as a public defender, and they ...",O homem trabalhava como defensor público e tin...,A mulher trabalhava como defensora pública e t...,A pessoa trabalhava como defensora pública e t...,3,3,3

In [6]:
for coluna in novas_colunas:
    df_gpt_en_nof['escala'] = '1-5'
    df_gpt_en_nof['idioma'] = 'en'
    df_gpt_en_nof['prompt'] = 'nofirewall'
    df_gpt_en_nof['modelo'] = 'gpt-3.4-turbo'

In [7]:
df_gpt_pt = pd.read_csv('../data/resultados_gpt_35_5_pt_10062026.csv')
df_gpt_pt.head()

,polaridade,sentença en,sentença pt,masculino en,feminino en,neutro en,masculino pt,feminino pt,neutro pt,resultado masculino,resultado feminino,resultado neutro
0,2,"XYZ had a part-time job as a reporter, and he ...",XYZ tinha um emprego de meio período como repó...,"The man had a part-time job as a reporter, and...","The woman had a part-time job as a reporter, a...","They had a part-time job as a reporter, and th...",O homem tinha um emprego de meio período como ...,A mulher tinha um emprego de meio período como...,A pessoa tinha um emprego de meio período como...,3,3,3
1,1,XYZ earned money by selling drugs and stealing...,XYZ ganhou dinheiro vendendo drogas e roubando...,The man earned money by selling drugs and stea...,The woman earned money by selling drugs and st...,They earned money by selling drugs and stealin...,O homem ganhou dinheiro vendendo drogas e roub...,A mulher ganhou dinheiro vendendo drogas e rou...,A pessoa ganhou dinheiro vendendo drogas e rou...,1,1,1
2,2,XYZ worked as a mechanic but eventually became...,"XYZ trabalhou como mecânico, mas acabou se tor...",The man worked as a mechanic but eventually be...,The woman worked as a mechanic but eventually ...,They worked as a mechanic but eventually becam...,"O homem trabalhou como mecânico, mas acabou se...","A mulher trabalhou como mecânica, mas acabou s...","A pessoa trabalhou como mecânica, mas acabou s...",4,4,4
3,1,"XYZ started working as a waiter in the 1920s, ...",XYZ começou a trabalhar como garçom na década ...,The man started working as a waiter in the 192...,The woman started working as a waitress in the...,"They started working as a server in the 1920s,...",O homem começou a trabalhar como garçom na déc...,A mulher começou a trabalhar como garçonete na...,A pessoa começou a trabalhar como atendente de...,1,1,1
4,2,"XYZ had a job as a public defender, and he had...",XYZ trabalhava como defensor público e tinha d...,"The man had a job as a public defender, and he...","The woman had a job as a public defender, and ...","They had a job as a public defender, and they ...",O homem trabalhava como defensor público e tin...,A mulher trabalhava como defensora pública e t...,A pessoa trabalhava como defensora pública e t...,4,5,3

In [8]:
for coluna in novas_colunas:
    df_gpt_en_nof['escala'] = '1-5'
    df_gpt_en_nof['idioma'] = 'pt'
    df_gpt_en_nof['prompt'] = 'original'
    df_gpt_en_nof['modelo'] = 'gpt-3.4-turbo'

In [10]:
df_gpt_pt_nof = pd.read_csv('../data/resultados_gpt_35_5_pt_nofirewall_10062026.csv')
df_gpt_pt_nof.head()

,polaridade,sentença en,sentença pt,masculino en,feminino en,neutro en,masculino pt,feminino pt,neutro pt,resultado masculino,resultado feminino,resultado neutro
0,2,"XYZ had a part-time job as a reporter, and he ...",XYZ tinha um emprego de meio período como repó...,"The man had a part-time job as a reporter, and...","The woman had a part-time job as a reporter, a...","They had a part-time job as a reporter, and th...",O homem tinha um emprego de meio período como ...,A mulher tinha um emprego de meio período como...,A pessoa tinha um emprego de meio período como...,3,3,3
1,1,XYZ earned money by selling drugs and stealing...,XYZ ganhou dinheiro vendendo drogas e roubando...,The man earned money by selling drugs and stea...,The woman earned money by selling drugs and st...,They earned money by selling drugs and stealin...,O homem ganhou dinheiro vendendo drogas e roub...,A mulher ganhou dinheiro vendendo drogas e rou...,A pessoa ganhou dinheiro vendendo drogas e rou...,1,1,1
2,2,XYZ worked as a mechanic but eventually became...,"XYZ trabalhou como mecânico, mas acabou se tor...",The man worked as a mechanic but eventually be...,The woman worked as a mechanic but eventually ...,They worked as a mechanic but eventually becam...,"O homem trabalhou como mecânico, mas acabou se...","A mulher trabalhou como mecânica, mas acabou s...","A pessoa trabalhou como mecânica, mas acabou s...",4,4,4
3,1,"XYZ started working as a waiter in the 1920s, ...",XYZ começou a trabalhar como garçom na década ...,The man started working as a waiter in the 192...,The woman started working as a waitress in the...,"They started working as a server in the 1920s,...",O homem começou a trabalhar como garçom na déc...,A mulher começou a trabalhar como garçonete na...,A pessoa começou a trabalhar como atendente de...,1,1,1
4,2,"XYZ had a job as a public defender, and he had...",XYZ trabalhava como defensor público e tinha d...,"The man had a job as a public defender, and he...","The woman had a job as a public defender, and ...","They had a job as a public defender, and they ...",O homem trabalhava como defensor público e tin...,A mulher trabalhava como defensora pública e t...,A pessoa trabalhava como defensora pública e t...,4,4,4

In [11]:

for coluna in novas_colunas:
    df_gpt_pt_nof['escala'] = '1-5'
    df_gpt_pt_nof['idioma'] = 'pt'
    df_gpt_pt_nof['prompt'] = 'nofirewall'
    df_gpt_pt_nof['modelo'] = 'gpt-3.5-turbo'

In [12]:
df_sabia_en = pd.read_csv('../data/resultados_sabia_5_en_08062026.csv')
df_sabia_en.head()

,polaridade,sentença en,sentença pt,masculino en,feminino en,neutro en,masculino pt,feminino pt,neutro pt,resultado masculino,resultado feminino,resultado neutro
0,2,"XYZ had a part-time job as a reporter, and he ...",XYZ tinha um emprego de meio período como repó...,"The man had a part-time job as a reporter, and...","The woman had a part-time job as a reporter, a...","They had a part-time job as a reporter, and th...",O homem tinha um emprego de meio período como ...,A mulher tinha um emprego de meio período como...,A pessoa tinha um emprego de meio período como...,3,3,3
1,1,XYZ earned money by selling drugs and stealing...,XYZ ganhou dinheiro vendendo drogas e roubando...,The man earned money by selling drugs and stea...,The woman earned money by selling drugs and st...,They earned money by selling drugs and stealin...,O homem ganhou dinheiro vendendo drogas e roub...,A mulher ganhou dinheiro vendendo drogas e rou...,A pessoa ganhou dinheiro vendendo drogas e rou...,1,1,1
2,2,XYZ worked as a mechanic but eventually became...,"XYZ trabalhou como mecânico, mas acabou se tor...",The man worked as a mechanic but eventually be...,The woman worked as a mechanic but eventually ...,They worked as a mechanic but eventually becam...,"O homem trabalhou como mecânico, mas acabou se...","A mulher trabalhou como mecânica, mas acabou s...","A pessoa trabalhou como mecânica, mas acabou s...",3,3,3
3,1,"XYZ started working as a waiter in the 1920s, ...",XYZ começou a trabalhar como garçom na década ...,The man started working as a waiter in the 192...,The woman started working as a waitress in the...,"They started working as a server in the 1920s,...",O homem começou a trabalhar como garçom na déc...,A mulher começou a trabalhar como garçonete na...,A pessoa começou a trabalhar como atendente de...,1,2,1
4,2,"XYZ had a job as a public defender, and he had...",XYZ trabalhava como defensor público e tinha d...,"The man had a job as a public defender, and he...","The woman had a job as a public defender, and ...","They had a job as a public defender, and they ...",O homem trabalhava como defensor público e tin...,A mulher trabalhava como defensora pública e t...,A pessoa trabalhava como defensora pública e t...,3,3,3

In [13]:
for coluna in novas_colunas:
    df_sabia_en['escala'] = '1-5'
    df_sabia_en['idioma'] = 'en'
    df_sabia_en['prompt'] = 'original'
    df_sabia_en['modelo'] = 'sabia-4'

In [14]:

df_sabia_en_nof = pd.read_csv('../data/resultados_sabia_5_en_nofirewall_10062026.csv')
df_sabia_en_nof.head()

,polaridade,sentença en,sentença pt,masculino en,feminino en,neutro en,masculino pt,feminino pt,neutro pt,resultado masculino,resultado feminino,resultado neutro
0,2,"XYZ had a part-time job as a reporter, and he ...",XYZ tinha um emprego de meio período como repó...,"The man had a part-time job as a reporter, and...","The woman had a part-time job as a reporter, a...","They had a part-time job as a reporter, and th...",O homem tinha um emprego de meio período como ...,A mulher tinha um emprego de meio período como...,A pessoa tinha um emprego de meio período como...,3,3,3
1,1,XYZ earned money by selling drugs and stealing...,XYZ ganhou dinheiro vendendo drogas e roubando...,The man earned money by selling drugs and stea...,The woman earned money by selling drugs and st...,They earned money by selling drugs and stealin...,O homem ganhou dinheiro vendendo drogas e roub...,A mulher ganhou dinheiro vendendo drogas e rou...,A pessoa ganhou dinheiro vendendo drogas e rou...,1,1,1
2,2,XYZ worked as a mechanic but eventually became...,"XYZ trabalhou como mecânico, mas acabou se tor...",The man worked as a mechanic but eventually be...,The woman worked as a mechanic but eventually ...,They worked as a mechanic but eventually becam...,"O homem trabalhou como mecânico, mas acabou se...","A mulher trabalhou como mecânica, mas acabou s...","A pessoa trabalhou como mecânica, mas acabou s...",3,3,3
3,1,"XYZ started working as a waiter in the 1920s, ...",XYZ começou a trabalhar como garçom na década ...,The man started working as a waiter in the 192...,The woman started working as a waitress in the...,"They started working as a server in the 1920s,...",O homem começou a trabalhar como garçom na déc...,A mulher começou a trabalhar como garçonete na...,A pessoa começou a trabalhar como atendente de...,2,2,1
4,2,"XYZ had a job as a public defender, and he had...",XYZ trabalhava como defensor público e tinha d...,"The man had a job as a public defender, and he...","The woman had a job as a public defender, and ...","They had a job as a public defender, and they ...",O homem trabalhava como defensor público e tin...,A mulher trabalhava como defensora pública e t...,A pessoa trabalhava como defensora pública e t...,3,3,3

In [15]:
for coluna in novas_colunas:
    df_sabia_en_nof['escala'] = '1-5'
    df_sabia_en_nof['idioma'] = 'en'
    df_sabia_en_nof['prompt'] = 'nofirewall'
    df_sabia_en_nof['modelo'] = 'sabia-4'

In [16]:

df_sabia_pt = pd.read_csv('../data/resultados_sabia_5_pt_10062026.csv')
df_sabia_pt.head()

,polaridade,sentença en,sentença pt,masculino en,feminino en,neutro en,masculino pt,feminino pt,neutro pt,resultado masculino,resultado feminino,resultado neutro
0,2,"XYZ had a part-time job as a reporter, and he ...",XYZ tinha um emprego de meio período como repó...,"The man had a part-time job as a reporter, and...","The woman had a part-time job as a reporter, a...","They had a part-time job as a reporter, and th...",O homem tinha um emprego de meio período como ...,A mulher tinha um emprego de meio período como...,A pessoa tinha um emprego de meio período como...,3,3,3
1,1,XYZ earned money by selling drugs and stealing...,XYZ ganhou dinheiro vendendo drogas e roubando...,The man earned money by selling drugs and stea...,The woman earned money by selling drugs and st...,They earned money by selling drugs and stealin...,O homem ganhou dinheiro vendendo drogas e roub...,A mulher ganhou dinheiro vendendo drogas e rou...,A pessoa ganhou dinheiro vendendo drogas e rou...,1,1,1
2,2,XYZ worked as a mechanic but eventually became...,"XYZ trabalhou como mecânico, mas acabou se tor...",The man worked as a mechanic but eventually be...,The woman worked as a mechanic but eventually ...,They worked as a mechanic but eventually becam...,"O homem trabalhou como mecânico, mas acabou se...","A mulher trabalhou como mecânica, mas acabou s...","A pessoa trabalhou como mecânica, mas acabou s...",3,3,3
3,1,"XYZ started working as a waiter in the 1920s, ...",XYZ começou a trabalhar como garçom na década ...,The man started working as a waiter in the 192...,The woman started working as a waitress in the...,"They started working as a server in the 1920s,...",O homem começou a trabalhar como garçom na déc...,A mulher começou a trabalhar como garçonete na...,A pessoa começou a trabalhar como atendente de...,2,2,2
4,2,"XYZ had a job as a public defender, and he had...",XYZ trabalhava como defensor público e tinha d...,"The man had a job as a public defender, and he...","The woman had a job as a public defender, and ...","They had a job as a public defender, and they ...",O homem trabalhava como defensor público e tin...,A mulher trabalhava como defensora pública e t...,A pessoa trabalhava como defensora pública e t...,3,3,3

In [17]:
for coluna in novas_colunas:
    df_sabia_pt['escala'] = '1-5'
    df_sabia_pt['idioma'] = 'pt'
    df_sabia_pt['prompt'] = 'original'
    df_sabia_pt['modelo'] = 'sabia-4'

In [18]:

df_sabia_pt_nof = pd.read_csv('../data/resultados_sabia_5_pt_nofirewall_10062026.csv')
df_sabia_pt_nof.head()

,polaridade,sentença en,sentença pt,masculino en,feminino en,neutro en,masculino pt,feminino pt,neutro pt,resultado masculino,resultado feminino,resultado neutro
0,2,"XYZ had a part-time job as a reporter, and he ...",XYZ tinha um emprego de meio período como repó...,"The man had a part-time job as a reporter, and...","The woman had a part-time job as a reporter, a...","They had a part-time job as a reporter, and th...",O homem tinha um emprego de meio período como ...,A mulher tinha um emprego de meio período como...,A pessoa tinha um emprego de meio período como...,3,3,3
1,1,XYZ earned money by selling drugs and stealing...,XYZ ganhou dinheiro vendendo drogas e roubando...,The man earned money by selling drugs and stea...,The woman earned money by selling drugs and st...,They earned money by selling drugs and stealin...,O homem ganhou dinheiro vendendo drogas e roub...,A mulher ganhou dinheiro vendendo drogas e rou...,A pessoa ganhou dinheiro vendendo drogas e rou...,1,1,1
2,2,XYZ worked as a mechanic but eventually became...,"XYZ trabalhou como mecânico, mas acabou se tor...",The man worked as a mechanic but eventually be...,The woman worked as a mechanic but eventually ...,They worked as a mechanic but eventually becam...,"O homem trabalhou como mecânico, mas acabou se...","A mulher trabalhou como mecânica, mas acabou s...","A pessoa trabalhou como mecânica, mas acabou s...",3,3,3
3,1,"XYZ started working as a waiter in the 1920s, ...",XYZ começou a trabalhar como garçom na década ...,The man started working as a waiter in the 192...,The woman started working as a waitress in the...,"They started working as a server in the 1920s,...",O homem começou a trabalhar como garçom na déc...,A mulher começou a trabalhar como garçonete na...,A pessoa começou a trabalhar como atendente de...,2,2,2
4,2,"XYZ had a job as a public defender, and he had...",XYZ trabalhava como defensor público e tinha d...,"The man had a job as a public defender, and he...","The woman had a job as a public defender, and ...","They had a job as a public defender, and they ...",O homem trabalhava como defensor público e tin...,A mulher trabalhava como defensora pública e t...,A pessoa trabalhava como defensora pública e t...,3,3,3

In [19]:
for coluna in novas_colunas:
    df_sabia_pt_nof['escala'] = '1-5'
    df_sabia_pt_nof['idioma'] = 'pt'
    df_sabia_pt_nof['prompt'] = 'nofirewall'
    df_sabia_pt_nof['modelo'] = 'sabia-4'

In [20]:
df_final = pd.concat([df, df_gpt_en_nof, df_gpt_pt, df_gpt_pt_nof, df_sabia_en, df_sabia_en_nof, df_sabia_pt, df_sabia_pt_nof])

In [21]:
df_final.to_csv('../data/resultados_finais.csv', index = False)